### ISSUE TITLE
Document that Alpine AJAX is only for Same-Page client-server interations.

### ISSUE THREAD

**Issue by bluz71** [imacrayon/alpine-ajax#101]
Hello @imacrayon,

I created issues #99 and #100 requesting HTMX Link Boost and Link preloading behaviour since other libraries such as HTMX and Hotwire Turbo provided them. Silly me was think with a 2015 mindset.

HTMX Boost is not necessary since Browsers are getting better, Chrome (and derivatives) now support Multi-Page View Transitions and `speculationrules` link preloading. Other browsers are following Chrome's lead.

So there is absolutely no need for Alpine AJAX to provide support for features that browsers are now providing for free (once the appropriate directives are set, see #99 and #100).

This request is asking that Alpine AJAX website to be updated with the following type of documentation (somewhere):

- Alpine AJAX is strictly a Same-Page client <-> server interaction library, for example, adding content such as infinite scroll, modifying content (such as tabbed content) or deleting elements on **the current page**
- Alpine AJAX is not intended for Page-to-Page behaviour such as HTMX Boost or Turbo Drive, those capabilities are now natively supported in the most modern browsers via Multi-Page Transitions and `speculationrules` whilst avoiding all the issues (such as JS not being reloaded on a HTMX Boost page change).

Documentation would be helpful to other novices who like me think HTMX Boost is necessary for smooth SPA-like page changes.

Up to you @imacrayon, if you don't do it, no big deal either, it just may be useful to stop people pestering you about HTMX Boost.

Sorry for posting so much.

Best regards.

**Comment by imacrayon** [comment]
Hey Dennis, thanks for all the research! 

For sure I think it makes sense to add this info to the docs, I'll work it in with the new release we're tagging soon.

**Comment by Fak3** [comment]
> * now natively supported in the most modern browsers

How is page-to-page transitions actually supported? When I click back button, the page does not change at all, as described in #93 - I have to manually reload the whole page on 'popstate' event to see the previous page content.

**Comment by bluz71** [comment]
> How is page-to-page transitions actually supported?

See [this comment](https://github.com/imacrayon/alpine-ajax/issues/99#issuecomment-2418679958). Just add in the simple CSS directive to your top level CSS.

All modern Chrome-derived browsers support multi-page view transitions (since Chrome 126 - June 2024). That includes Chrome, Edge and Brave browsers.

Safari and Firefox, not yet, but work is being done there as well.

If a browser does not yet support multi-page view transition, a full page reload will occur when going from page to page. This used to result in a very noticeable flash, but these days the flash is quite minor (browsers are better and faster now compared with 5-10 years ago).

Multi-view page transition is a progressive enhancement, if the browser supports it, great, if not, that is not bad either.

Messing with popstate should not be necessary, don’t use JavaScript for any page to page transition, leave that to the browser, old-school style, but do add the CSS to enable multi-page view transitions.

**Comment by imacrayon** [comment]
Also since around 2019 modern browsers all support "paint holding" which means you won't get any flash of a blank white screen between page loads, this also goes a long way toward making website navigation feel faster: https://developer.chrome.com/blog/paint-holding/

**Comment by bluz71** [comment]
Agreed, flash is very minor, almost non-existent. I have to try hard to see. Very different compared to Turbolinks days around 2015 era.

Multi-page view transitions are nicer, page changes are smooth as silk. Just add the CSS once, instant win for all Chrome-like browsers.

Safari and Firefox support is coming.

Everyone wins and less work for library authors such as @imacrayon.

**Comment by bluz71** [comment]
@imacrayon,

Just noting, it appears that Safari 18 (released Sep 16 2024) now supports Same-Page View Transitions.

[See here](https://webkit.org/blog/15865/webkit-features-in-safari-18-0/), go to the View Transitions section.

Multi-Page View Transitions not yet supported, I tested it, confirmed not working. Though I fully expect MP VT in Safari to come in the not too distant future.

Exciting times. View Transitions is a massive win for old-school Laravel, Rails, Django multi-page apps.

**Comment by bluz71** [comment]
Thank you @imacrayon.

What a time to be alive. I can't believe how good browsers are getting, even in just the past couple of months.

The humble Multi-Page-App is back in town, better than ever.

Keep Alpine AJAX small, win win win.

**Comment by bluz71** [comment]
Hello @imacrayon,

_"Cross-document View Transitions"_ (aka Apple's name for Multi-Page View Transitions) is coming to Safari 18.2.

See [these 18.2 beta release notes](https://developer.apple.com/documentation/safari-release-notes/safari-18_2-release-notes).

18.1 is the current release of Safari.

So, the next release of Safari will contain this excellent feature.

Not long to wait.
