### ISSUE TITLE
Target [#form] was not found in current document

### ISSUE THREAD

**Issue by Jagadish056** [imacrayon/alpine-ajax#105]
**Steps to Reproduce:**
- Open the [Laravel Playground](https://laravelplayground.com/).
- Copy and paste the following code into `playground.blade.php` and run it.
- Switch from `Tab 1` to `Tab 2`, then from `Tab 2` to `Tab 3`.
- Click the `button` in Tab 3.
- Check the console for an error.

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Laravel Playground</title>
    <script defer src="https://cdn.jsdelivr.net/npm/@imacrayon/alpine-ajax@0.9.1/dist/cdn.min.js"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/@alpinejs/morph@3.x.x/dist/cdn.min.js"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.14.3/dist/cdn.min.js"></script>
</head>
<body>
    <section id="section-1" x-merge="morph">
        <form x-target="section-1" method="get">
            <nav>
                @foreach (['Tab 1', 'Tab 2', 'Tab 3'] as $tab)
                    <button type="submit" name="tab" value="{{ $tab }}">{{ $tab }}</button>
                @endforeach
            </nav>
        </form>

        @switch(request()->input('tab'))
            @case('Tab 2')
                Default Text 2
                <form id="form-1" method="post" x-target>
                    @csrf
                    {{-- <button type="submit">Button</button> --}}
                </form>
                @break
            @case('Tab 3')
                Default Text 3
                <form id="form-2" method="post" x-target>
                    @csrf
                    <button type="submit">Button</button>
                </form>
                @break
            @default
                Default Text 1
        @endswitch
    </section>
</body>
</html>
```

**Comment by Jagadish056** [comment]
Thanks for the quick fixes! I’ve been waiting all day, and it seems to be working perfectly now.

**Comment by Jagadish056** [comment]
Hey @imacrayon, sorry to trouble you again!

Without `Morph`, all content gets refreshed (_not a browser reload_ 🔄)  when switching tabs. What happens if I use all three: `Morph`, `x-autofocus`, and `key`? Could this cause issues in the future?

```
<section x-merge="morph">
    ...
        <button @if($activeTab) x-autofocus @endif>{{ $tab }}</button>
    ...

    <div key="{{ now() }}">
        @switch(true)
            @case(1)
                ...
                @break
            @case(2)
                ...
                @break
            @default
                ...
        @endswitch
    </div>
</section>
```

**Comment by imacrayon** [comment]
Using all of those together shouldn't cause problems. I'd file an issue if you find something though. One thing to note: If you're using Morph you probably don't need `x-autofocus` since Morph should automatically preserve keyboard focus for you.

**Comment by Jagadish056** [comment]
Alright, I'll keep that in mind, but one question remains: in this video [?v=31pBMi0UdYE&t=1637s](https://youtu.be/31pBMi0UdYE?t=1637), he's explaining the concept of _Roving Tab Index_. Is this currently possible with Alpine AJAX?

**Comment by imacrayon** [comment]
You can issue the request on `focus` like this: `x-on:focus="$ajax('?tab1', {target: 'tab1_content'})`

Alternatively, you could use the `x-intersect` plugin and issue the same AJAX request when a tab is revealed.
