### ISSUE TITLE
Multi button form ajax question

### ISSUE THREAD

**Issue by florian-sun** [imacrayon/alpine-ajax#108]
This is not an issue, just a request for help. I don't see any Discussions tag so I'm asking here. If this is not appropriate, let me know and I'll delete this post.
So here is my setup. I have a form with several buttons, each with its own handler. Each button must do some stuff and then shd perform a different AJAX transformation.
Is this possible?

**Comment by imacrayon** [comment]
It might help if you had an example, but yes - you can multiple buttons in the same form submit to different endpoints.

Using `form` attribute:
```
<form method="post" action="/update">
  <button>Update</button>
  <button form="delete_form">Delete</button>
</form>
<form method="post" action="/delete" id="delete_form"></form>
```

Using `formaction`/`formmethod` attributes:
```
<form method="post" action="/update">
  <button>Update</button>
  <button formaction="post" formmethod="/delete">Delete</button>
</form>
```

**Comment by florian-sun** [comment]
Thanks, but, as I said, the buttons have their own handlers already, doing stuff different than submitting the form. So I don't actually want to submit the form, I just want the AJAX functionality. I will provide an example later

**Comment by florian-sun** [comment]
Here is an example, sort of:

<body>   
  <form x-data="{ f1( ){...}, f2( ){...} }">
    <button @click="f1( )">button1</button> // fetch some html and shd x-target id1
    <button @click="f2( )">button2</button> // fetch some html and shd x-target id2
  </form>
</body>

**Comment by imacrayon** [comment]
Ah, sorry, I missed your follow up message @florian-sun. But ditto to Justis’s suggestion 👍

**Comment by imacrayon** [comment]
Closing this issue, but feel free to re-open it if you have any further questions.
