### ISSUE TITLE
Dropzone.js Usage?

### ISSUE THREAD

**Issue by compilekaiten** [imacrayon/alpine-ajax#11]
Hi, is this something that could be used with Dropzone.js? 

I have a Dropzone form that opens a modal when Dropzone fires the success event. Rather than returning JSON from my backend, parsing it, and updating the Modal info (which is my current approach, and rather tedious), I wanted to use this, to return an html snippet that would fill the modal. 

Being a JS novice, I wasn't able to figure out a way to do this. Maybe it's a Dropzone limitation?

Thanks!

**Comment by imacrayon** [comment]
I’ve never used Dropzone, but just checking the docs, you might be able to use `x-load` and listen for the `addedfile`.
```html
<div id=“file” x-data x-load:addedfile=“/url/to/uploaded/file/info”></div>
```

So when `addedfile` bubbles up to the `window` it should trigger this div to make a request to `/url/to/uploaded/file/info`. Remember to include something with `id=“file”` in the response so content is swapped correctly.

**Comment by compilekaiten** [comment]
> I’ve never used Dropzone, but just checking the docs, you might be able to use `x-load` and listen for the `addedfile`.
> 
> ```html
> 
> <div id=“file” x-data x-load:addedfile=“/url/to/uploaded/file/info”></div>
> 
> ```
> 
> 
> 
> So when `addedfile` bubbles up to the `window` it should trigger this div to make a request to `/url/to/uploaded/file/info`. Remember to include something with `id=“file”` in the response so content is swapped correctly.
> 
> 

Thanks. That's perfect. Great library.

**Comment by imacrayon** [comment]
Just wanted to pop in a note that this syntax was changed in v0.1:

```
<div id=“file @addedfile=“$ajax(‘/url/to/uploaded/file/info’)”></div>
```
