### ISSUE TITLE
Are view transitions broken?

### ISSUE THREAD

**Issue by SmileyChris** [imacrayon/alpine-ajax#111]
I've been trying `x-merge.transition` out myself and can't get it to work.

The [inline edit](https://alpine-ajax.js.org/examples/inline-edit/) demo is supposed to use this according to what I see in the code, but the form isn't transitioning for me either (in chrome, with other non alpine-ajax view transitions working).

**Comment by imacrayon** [comment]
Hi, thanks for reporting this. Yeah, I'm seeing the same thing. What's weird is it's working locally for me but not on production, so it might just be a deployment issue...I'll do some more digging.

**Comment by SmileyChris** [comment]
Thanks for the super quick fix!
Fixed in fde17785c9a88da24a9e1c9e75c38a96dc593249, reased in [v0.10.3](https://github.com/imacrayon/alpine-ajax/releases/tag/v0.10.3).
