### ISSUE TITLE
Multiple simultaneous `$ajax` calls to the same URL cancels the request

### ISSUE THREAD

**Issue by SmileyChris** [imacrayon/alpine-ajax#117]
I have a situation where a websocket was sends updates back to the browser.
These send a window custom message that alpine is listening for and then triggering an `$ajax` to update some stuff.
If I get two updates at the same time, the request is cancelled.

![image](https://github.com/user-attachments/assets/504a1ab7-3820-446e-bd38-a9d4a587f5be)

**Comment by SmileyChris** [comment]
If these messages occur over time, it's fine, hence why I think it's only when there are simultaneous requests.

Here's an example of three requests working fine if they don't happen at the same moment:
![image](https://github.com/user-attachments/assets/37a7eb8a-0ae2-4bb1-ae71-d5ce804a82ad)

**Comment by imacrayon** [comment]
Hey thanks for reporting this. So the intended behavior is that a request will be cancelled if a new request is issued that targets the same element. 
In the code a “stale” request is cancelled using the `_ajax_abort` method. I think there might be a race condition somewhere that is causing this method to run too soon.
I can take a look into it later this week, but if anyone wants to dive in, I’d welcome a PR too.

**Comment by SmileyChris** [comment]
I found another similar situation with a search field. Because I had the @search, it was triggering two times simultaneously if I press enter, entirely cancelling the request. Worse is that it's cancelled forever: that search phrase never works again until a refresh.

```
        <form
          method="GET"
          action="."
          role="search"
          x-init
          x-target="games"
        >
          <input
            type="search"
            placeholder="Search games..."
            name="q"
            value="{{ text_filter|default:'' }}"
            @input.debounce="$el.form.requestSubmit()"
            @search="$el.form.requestSubmit()"
          />
        </form>
```

Now granted, the fix is to just get rid of the `@search` event handler. But I can reproduce it without this by hitting enter rapidly even after this line is removed. Again, once it is cancelled, it never works again.

**Comment by SmileyChris** [comment]
Failing here:
![image](https://github.com/user-attachments/assets/6790c046-e587-4623-a98e-9e100b3eb833)
![image](https://github.com/user-attachments/assets/7f3e03b5-81e3-4746-b3ec-bfab28f5c460)

**Comment by imacrayon** [comment]
> I found another similar situation with a search field.

Thanks for this reproduction, that helps narrow things down. Sorry for the delay in getting to this, I wonder if there's an issue where `_ajax_abort` is being defined.  The method gets defined on a targeted DOM Element, so if two requests share the same target element `_ajax_abort` will get redefined mid-request. Something might be screwing up in that case.

**Comment by imacrayon** [comment]
Alright, I'm able to reproduce this on my end. `ResponseCache` isn't being flushed when a request is aborted, so the aborted request will be re-used on every subsequent request. Working on a fix now...
