### ISSUE TITLE
how the response looks like

### ISSUE THREAD

**Issue by ericxin1982** [imacrayon/alpine-ajax#14]
![image](https://github.com/imacrayon/alpine-ajax/assets/9047436/ffb02d41-da40-4d08-ac47-b1eb6d2f0b63)

Hi @imacrayon 

If there is multiple targets defined, not sure how the responses look like, would you please give me a picture?

Thanks
Eric Xin

**Comment by imacrayon** [comment]
Hey, thanks for the question. The response must contain valid HTML and the two IDs that you're targeting.

So you could return the exact same HTML markup with a new comment and updated count like this:

```html
<h2>Comments (<span id="comments_count">2</span>)</h2>
<ul id="comments">
  <li>Comment #1</li>
  <li>Comment #2</li>
</ul>
<h2 id="comment_form_title">Post a Comment</h2>
<form x-target="comments comments_count" method="post" action="/comment" aria-labelledby="comment_form_title">
  <input name="comment" required />
  <button>Submit</button>
</form>
```

or you could return only the elements you targeted:

```html
<h2>Comments (<span id="comments_count">2</span>)</h2>
<ul id="comments">
  <li>Comment #1</li>
  <li>Comment #2</li>
</ul>
```
or you could return a complete HTML document:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Post a comment</title>
  </head>
  <body>
    <h1>Post a comment</h1>
    <h2>Comments (<span id="comments_count">2</span>)</h2>
    <ul id="comments">
      <li>Comment #1</li>
      <li>Comment #2</li>
    </ul>
    <h2 id="comment_form_title">Post a Comment</h2>
    <form x-target="comments comments_count" method="post" action="/comment" aria-labelledby="comment_form_title">
      <input name="comment" required />
      <button>Submit</button>
    </form>
  </body>
</html>
```

All these options will work, the only thing that matters is that there is a `id="comments"` element and a `id="comments_count"` element in the response.

Let me know if that clears things up and I'll update the documentation with an example response.

**Comment by ericxin1982** [comment]
Hi @imacrayon 

![image](https://github.com/imacrayon/alpine-ajax/assets/9047436/3ab467be-e83e-4adb-8300-b19e50e36c39)
I prefer this way, then the response txt would be both together right?
So x-target would separately place two elements in right target anchor, that is what I am cuious.

If the response txt is just for one element, and target is one location anchor, I do not have this question.
I am just curious about the detail whether need to split them, or if no, how it can place the right element from many elements to right anchor.

The tutorial just mentioned it has this multiple target feature.

Thanks for your help. Waiting for your instructions.

Eric Xin

**Comment by imacrayon** [comment]
> how it can place the right element from many elements to right anchor.

All the elements have to exist on the page, before the request so that Alpine AJAX knows where to place them. So if you use `x-target="comments comments_count"` and your HTML looks like this (no `comments_count` element):

```html
<h2>Comments (0)</h2>
<ul id="comments">
</ul>
<form x-target="comments comments_count">...</form>
```

You'll get an error in the console because `id="comments_count"` doesn't exist on the page.

<img width="1060" alt="Screenshot 2023-06-19 at 12 37 15 PM" src="https://github.com/imacrayon/alpine-ajax/assets/3410149/e91cb26e-2e74-4a7d-9772-af1085c1283d">

[Here's a CodePen of the comment form you can explore](https://codepen.io/imacrayon/pen/oNQLBEp)

**Comment by ericxin1982** [comment]
Thanks so much, so the library would handle the ID anchor respectively, so I can render all elements with different ID, then rest of them the library would handle.
