### ISSUE TITLE
like hyperscript that way to add

### ISSUE THREAD

**Issue by ericxin1982** [imacrayon/alpine-ajax#15]
Hi @imacrayon 

First picture is htmx + hyperscript.
![image](https://github.com/imacrayon/alpine-ajax/assets/9047436/5669ce8a-afc9-4d58-89ab-72de396b70cf)

Second picture is alpine + alpine ajax
![image](https://github.com/imacrayon/alpine-ajax/assets/9047436/009007fa-b93c-41fe-b44a-4f477f3477a2)

I saw they have difference,  hyperscript seems not use the openmodel function, and add class directly, and you have openmodal this function involved, just wondering whether you need to add modal library as well, just not sure where it comes from, and just wondering if I want to use add class that way, is it possible, if that works, how to do?

Thanks
Eric Xin

**Comment by imacrayon** [comment]
Hi Eric, the Alpine AJAX example uses a native [HTML Dialog](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog), no extra library is required.

There are a few ways you could add a class with Alpine. If the modal element already has an `id` I would use `ajax:before=“document.getElementById('modal’).classList.add(‘uk-open’)”` but you could also use [x-ref](https://alpinejs.dev/directives/ref) to select the modal or [:class](https://alpinejs.dev/directives/bind#binding-classes) to add the modal class.

**Comment by ericxin1982** [comment]
Hi @imacrayon 

I prefer the modal is got by alpine ajax, and then add the top element downloaded by alpine ajax has 'uk-open' class, so I prefer to use alpine ajax event to add class, not alpine event to add class.

Do you think it is possible?
The htmx && Hyperscript that case is using Hyperscript event to add class, after downloaded.

Thanks
Eric Xin

**Comment by imacrayon** [comment]
> The htmx && Hyperscript that case is using Hyperscript event to add class, after downloaded.

You can listen for the `ajax:after` event instead of `ajax:before` to set your class after the download:

```
@ajax:after=“document.getElementById('modal’).classList.add(‘uk-open’)”
```

**Comment by ericxin1982** [comment]
Hi @imacrayon 

This @ajax:after is alpine.ajax has, or alpine has?

Thanks
Eric Xin

**Comment by ericxin1982** [comment]
Hi @imacrayon 

You know @ajax:after then I need to extract the html string from response, then I need to place into the right element, I may need to wait for a bit, is there a wait function or something else I can use to delay 10 or 20ms after @ajax:after?

Thanks
Eric Xin

**Comment by imacrayon** [comment]
> This `@Ajax:after` is alpine.ajax has, or alpine has?

It's an event fired by Alpine AJAX, you can see them all here: https://alpine-ajax.js.org/reference/#ajax-events

> I prefer the modal is got by alpine ajax

Sorry, i didn't understand this at first but, I get what you are saying now. I put together an example here: https://codepen.io/imacrayon/pen/KKrgmgZ

Instead of selecting the modal after the response, I would add `x-init` on the modal, the `x-init` will automatically run when the modal is added to the page.

**Comment by ericxin1982** [comment]
Thanks so much!
I got the point now.
