### ISSUE TITLE
web component solution

### ISSUE THREAD

**Issue by ericxin1982** [imacrayon/alpine-ajax#16]
Hi @imacrayon 

Just wondering whether you can provide me a suggestion, if I am using alpine, and I need web component for it, which framework or library I can use to build with?

Like web component as template, and I can use it together, something like that.

Thanks
Eric Xin

**Comment by imacrayon** [comment]
I use [Tailwind UI](https://tailwindui.com/) & [Alpine Components](https://alpinejs.dev/components) the most;
[Awesome Standalones](https://github.com/davatron5000/awesome-standalones) is a good resource for extra components; [GitHub’s Autocomplete](https://github.com/github/auto-complete-element) is what I use if I need an autocomplete field in my projetcs.

**Comment by ericxin1982** [comment]
Thanks for your advise!
