### ISSUE TITLE
Question: How to use select over buttons on filter content example?

### ISSUE THREAD

**Issue by nunowar** [imacrayon/alpine-ajax#20]
Hi,

I'm testing the Alpine AJAX in a WordPress project, and would like to know the best way to filter content based on the select box.

Same as here (https://alpine-ajax.js.org/examples/filterable-content/) but with select box instead of buttons.

Thanks.

**Comment by imacrayon** [comment]
Hi Nuno,

So this would be kind of a cross between the [Filterable Content](https://alpine-ajax.js.org/examples/filterable-content) you mentioned and the [Instant Search](https://alpine-ajax.js.org/examples/instant-search) example.

I would suggest building your filter form like this:

```html
 <form x-init x-target="contacts" action="/contacts" aria-label="Filter contacts" x-target="contacts">
   <label for="filter">Filter by:</label>
   <select id="filter" name="filter" @input="$el.form.requestSubmit()">
      <option value="active">Active</button>
      <option value="inactive">Inactive</button>
   </select>
   <button x-show="false">Search</button>
 </form>
 ```
 
 The `@input` event on the `<select>` submit the form whenever the select option changes. The `x-show="false"` on the `<button>` will hide the button when JavaScript is enabled, but show it in cases when JS might fail to load.

**Comment by nunowar** [comment]
Thanks!
