### ISSUE TITLE
Redirects don't work

### ISSUE THREAD

**Issue by delaneyj** [imacrayon/alpine-ajax#24]
If a POST send a 302 it should support changing the window.location.  This can happen for example with a validated form instead of returning an updated form with errors it sends the user to the newly created resource.

**Comment by gabriel-aires** [comment]
I second this. The existing functionality of alpine-ajax is great already. The only thing preventing me from using it instead of htmx is the handling of redirects after form submissions.

**Comment by imacrayon** [comment]
This makes sense. I've been leaving `x-target` off of forms when I want them to redirect, but now I realize doing so creates an inconsistent validation experience.

I'll play around with this and figure out what would make a good default. I think there would also need to be a `x-target.follow` modifier or something in cases when you might not want `window.location` to change.

**Comment by gabriel-aires** [comment]
Additionaly, I'd just like to say thank you for the amazing work on this library. The API is a breeze of fresh air compared with the alternatives.

**Comment by delaneyj** [comment]
:rocket:
