### ISSUE TITLE
Example "Instant Search" offline.

### ISSUE THREAD

**Issue by slopesweb** [imacrayon/alpine-ajax#3]
https://imacrayon.github.io/alpine-ajax/examples/active-search

**Comment by imacrayon** [comment]
This should be fixed now. Thanks for the heads up!

**Comment by slopesweb** [comment]
@imacrayon I discovered alpine js yesterday, as a cheap alternative to vuejs for basic stuff, and your lib is saving my day. Many thanks my good man.  Happy New Year to you and your family. :)
