### ISSUE TITLE
`x-target` - "forcing" the use of ID

### ISSUE THREAD

**Issue by adamkiss** [imacrayon/alpine-ajax#34]
Is there a reason the x-target is found via `getElementById`, rather than `querySelector`, this allowing use of `body` as the target (or even a class like `js-whatever-target`?

**Comment by imacrayon** [comment]
I went with IDs to keep consistent with HTML: `for`, `target`, `form`, `aria-labelledby`, `aria-controls`, etc. all use element IDs.
