### ISSUE TITLE
Title and meta tags don't updated

### ISSUE THREAD

**Issue by alnuaimi94** [imacrayon/alpine-ajax#40]
Hi, how can i make html head updated for each page when i use ajax request in links

**Comment by imacrayon** [comment]
Hey Abdullah, Alpine AJAX doesn't currently support full page navigation. If there's enough interest in that feature I'd consider adding it (PRs are welcome too), but there's a lot of accessibility and state concerns we'd need to get right with full client-side routing (one of the reasons I've been putting it off 😄).
Personally, I like to drop https://instant.page/ into my projects; I think preloaded links go a long way in making apps feel fast without having to mess with client-side routing edge cases.

**Comment by jonasfeige** [comment]
> Hey Abdullah, Alpine AJAX doesn't currently support full page navigation. If there's enough interest in that feature I'd consider adding it (PRs are welcome too), but there's a lot of accessibility and state concerns we'd need to get right with full client-side routing (one of the reasons I've been putting it off 😄). Personally, I like to drop https://instant.page/ into my projects; I think preloaded links go a long way in making apps feel fast without having to mess with client-side routing edge cases.

Just wanted to say that full page navigation would actually be an amazing feature and allow me (and many others) to fully replace HTMX / Turbo in a lot of projects.

**Comment by imacrayon** [comment]
I'm closing this issue as "won't fix" for now. There's a [Navigation section that was recently added to the documentation](https://alpine-ajax.js.org/reference/#navigation) which explains my current thinking on SPA-style navigation. There's also some further discussion around this topic on PR #65.
