### ISSUE TITLE
Can't self target on `<form>` when it has `x-merge`

### ISSUE THREAD

**Issue by DrSensor** [imacrayon/alpine-ajax#41]
I found out `x-target` cannot be blank (self-target) on `<form>` when there is `x-merge`. For example:
```html
<form id=user x-init x-target x-merge=after method=post action=/create/users>
  <button>Create</button> <!-- Uncaught (in promise) Missing Target: #[object HTMLInputElement] was not found in the current document. -->
</form>
```
Is this intentional?

(I've not yet test for other `x-merge` pattern)

**Comment by imacrayon** [comment]
Nope, not intentional. Thanks for reporting this!

**Comment by imacrayon** [comment]
@DrSensor I tried reproducing the issue here: https://codepen.io/imacrayon/pen/vYbqqob
I seems to be working though. Could it be that the content you are appending doesn't have a container with `id=user`?

**Comment by DrSensor** [comment]
Now I'm not sure what is happening. I will reopen this when I can reproduce it (need to grok my commit history 😂)
