### ISSUE TITLE
TypeError in latest version

### ISSUE THREAD

**Issue by jorisnoo** [imacrayon/alpine-ajax#48]
Hi there, and thank you very much for all your effort on this great plugin!

Unfortunately i'm running into the following error on the latest version when using `x-target`, seems to be related to a recent feature.

```
TypeError: can't access property "hasAttribute", event.submitter is null

if (event.submitter.hasAttribute("formnoajax")) {
      return;
}
```

**Comment by imacrayon** [comment]
Sorry about that [v0.4.3 should fix it](https://github.com/imacrayon/alpine-ajax/commit/1486a27e6ca65583c43af27cec53aa9d6115d87b).

Thanks for taking the time to report this!

**Comment by jorisnoo** [comment]
Thank you!
