### ISSUE TITLE
`MissingIdError` error thrown when using `x-target.replace` without an ID

### ISSUE THREAD

**Issue by jannbar** [imacrayon/alpine-ajax#53]
Hey @imacrayon,

thank you for all the work you put into this plugin! Really appreciate it!

I found a small bug – I have a form that looks like this:

```html
<form x-init x-target="customer-table" x-target.replace></form>
```

Everything works as expected, but I get this error in the console:

```
Uncaught Missing ID: <form x-init="" x-target="customer-table" x-target.replace=""> is missing an ID to target.
```

When I add an `id` to the form, the error disappears. If the ID is required, the docs should probably tell this – but I don't think it's required, because everything works? 🤔 

Maybe you can have a look.

TIA & Greetings from Germany!

**Comment by imacrayon** [comment]
Hi! Instead of using multiple `x-target`s on the element, `x-target.replace="customer-table" should work.
I should have provided a more complete example in the docs, so thanks for reaching out.

**Comment by jannbar** [comment]
Ah that makes sense – thank you!
