### ISSUE TITLE
Calling $ajax from code outside of Alpine.js

### ISSUE THREAD

**Issue by jonnitto** [imacrayon/alpine-ajax#54]
Currently it is not possible to call the `$ajax` functions outside of Alpine.js

Would it technically be possible to have exported theese functions so that they will be usable outside of Alpine.js?

**Comment by imacrayon** [comment]
Yeah it’s technically possible with some refactoring…The API would have to change a little bit to fill in the missing context that Alpine provides. 
My fear is if I expose that function there could be a lot of breakage between releases. The internals of this plugin are changing a lot, while I’m still figure out how things should work, and exposing them would mean more things that I have to track and document.

**Comment by jonnitto** [comment]
I solved this now by fire a custom event, and an alpine component is reacting to this… 😆

**Comment by jonnitto** [comment]
And, btw: Great plugin with a very nice website!

**Comment by imacrayon** [comment]
> I solved this now by fire a custom event, and an alpine component is reacting to this… 😆

Nice! Events FTW
