### ISSUE TITLE
Use ajax:success to preload assets (js)

### ISSUE THREAD

**Issue by jonnitto** [imacrayon/alpine-ajax#55]
If the response is ok, the event `ajax:success` get's fired. I use this event to search in the markup for missing Alpine JS Plugins. As the plugins must have been loaded before the markup appears on the page, it would be nice to have a `preventDefault` option with  a function in details who can be called to continue the work.

Pseudo-Code

```js
window.addEventListener('ajax:success', (event) => {
   event.preventDefault();
   const html = event.detail.response.html
   // do the needed stuff

   
   event.detail.render();
})
```

Like that It would be even possible the alter the markup:

```js
window.addEventListener('ajax:success', (event) => {
   event.preventDefault();
   const html = event.detail.response.html
   // do the needed stuff

   
   event.detail.render(html);
})
```

**Comment by imacrayon** [comment]
This was just release in v0.5 there's a very similar example to yours in the PR: https://github.com/imacrayon/alpine-ajax/pull/62

**Comment by jonnitto** [comment]
Awesome!!!! ❤️
