### ISSUE TITLE
Could not find a declaration file for module '@imacrayon/alpine-ajax'

### ISSUE THREAD

**Issue by michaylen** [imacrayon/alpine-ajax#57]
Could not find a declaration file for module '@imacrayon/alpine-ajax'. 'c:/Users/Michaylen/Desktop/laravel-app/node_modules/@imacrayon/alpine-ajax/dist/module.cjs.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/imacrayon__alpine-ajax` if it exists or add a new declaration (.d.ts) file containing `declare module '@imacrayon/alpine-ajax';`ts(7016)

VS Code

**Comment by imacrayon** [comment]
Hey thanks for reporting this. Do you have an idea of what might be the problem, or steps to reproduce? It looks Typescript related and I have no experience with Typescript 😬

**Comment by sparkcanon** [comment]
If you add a `env.d.ts` file with `declare module "@imacrayon/alpine-ajax";` in it. That should fix the error 🤞🏼

**Comment by imacrayon** [comment]
I'm gonna close this out, but feel free to reopen if sparkcanon's suggestion didn't work.
