### ISSUE TITLE
Any way to make incoming html replace the innerHTML of target instead of the whole target?  

### ISSUE THREAD

**Issue by nmabhinandan** [imacrayon/alpine-ajax#63]
Not having this option is making it awkward to handle server side html generation for full page refreshes. Is this on the roadmap or is there a reason why this intentionally is left out? This can be an x-merge option.

**Comment by imacrayon** [comment]
Hey, yes, full page refreshes are what I’m starting to work on right now.
My initial plan is to support merging the `<head>` element, announcing page changes for tools like screen readers, and caching back/forward history.

**Comment by wout** [comment]
@imacrayon That's great to hear! I was also looking at it and preparing a proposal PR to start a conversation. But it sounds like you have a clear vision already. 🤓️
