### ISSUE TITLE
Polling support?

### ISSUE THREAD

**Issue by fatherofinvention** [imacrayon/alpine-ajax#69]
Hello. Alpine-Ajax is awesome, so thank you! I'm wondering if polling is possible, like in HTMX: https://htmx.org/docs/#polling

**Comment by imacrayon** [comment]
There’s not a fancy API for it, but throw a `$ajax()` call inside a `setTimeout` or `setInterval` and you’ve got polling. This example does some polling to update a progress indicator: https://alpine-ajax.js.org/examples/progress-bar/
