### ISSUE TITLE
Question: Fetch and headers

### ISSUE THREAD

**Issue by eydun** [imacrayon/alpine-ajax#74]
Thanks for this awesome project.

I am using some server-side php-code that checks if the request is made by ajax, by examining if 'X-Requested-With' is set to 'XMLHttpRequest' in headers. 

Is it possible to add values to the headers, when using Alpine-Ajax?

**Comment by imacrayon** [comment]
Yes, you can use the [`x-header` directive](https://alpine-ajax.js.org/reference/#x-headers) to set headers per request or the [`headers` key in the global config](https://alpine-ajax.js.org/reference/#x-headers) to set the same header for every request.

Every AJAX request also includes the `X-Alpine-Request: true` and `X-Alpine-Target: {target ids}` headers by default.
