### ISSUE TITLE
Website examples are currently not working

### ISSUE THREAD

**Issue by P4ulJC** [imacrayon/alpine-ajax#80]
Hi,

Just in case you are not aware of it, the examples on the website (https://alpine-ajax.js.org/examples/)  are not working currently in Firefox or Chrome. They were working a couple of days ago.

The error as reported in Firefox: Uncaught (in promise) TypeError: t.status is undefined in function statusKey(attributes, response) at module.ems.js line 472, which is: let status = response.redirected ? "3xx" : response.status.toString();

In Chrome: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString') at rn (module.esm.js:472:62)

**Comment by imacrayon** [comment]
ooof 🤦 I definitely need to get those pages added to the test suite

They should be good to go now! Thanks for letting me know 🙌

**Comment by P4ulJC** [comment]
All working again.  Excellent! Thanks for fixing.
