### ISSUE TITLE
Add a Tabs example to the documentation

### ISSUE THREAD

**Issue by imacrayon** [imacrayon/alpine-ajax#9]
People like tabs.

**Comment by imacrayon** [comment]
I haven’t found a big need for server-powered tabs yet. They’re fairly simple to build client-side with Alpine already. 

I’ll reopen this if I get more requests for tabs in the future.

**Comment by Jipok** [comment]
I'm new to hateoas. What's the best way to organize tabs using your plugin?
I saw an [example in htmx](https://htmx.org/examples/tabs-hateoas/), but it seems terrible to me. No matter how fast the server code is, there is still a noticeable network delay. It's okay when a tab opens for the first time, but loading it on each repeated click is terrible.

Well, actually, in some situations you really need to get new content every time. But for example, I'm making a site for chatting with llm where there is a list of chats. And I definitely want to cache each chat after opening. But I don't know how to do it nicely and correctly.

**Comment by imacrayon** [comment]
https://github.com/DannyMoerkerke/basic-service-worker is a great service worker resource.
