### ISSUE TITLE
Back button not working

### ISSUE THREAD

**Issue by Shadowfaxenator** [imacrayon/alpine-ajax#93]
I add a `x-target.push` url changes, but state is not saved in a history when making page navigation. How can I solve it?

**Comment by imacrayon** [comment]
Hey, thanks for bringing this to my attention. We used to trigger a page reload when navigating through history, but it looks like that got dropped in in v0.6. Anyway I think a more comprehensive solution is probably necessary now, I'll try to get something pushing in the next few days. In the meantime, you should be able to add the old v0.5 behavior back to your project with this event listener:

```
window.addEventListener('popstate', (e) => {
  if (!e.state || !e.state.__ajax) return

  window.location.reload(true)
})
```

**Comment by Dxuian** [comment]
is this still open ? ~hacktoberfest ?~

**Comment by imacrayon** [comment]
@Dxuian yeah sorry, I got sidetracked on some other issues. I'd accept a PR even if it's just a draft. I don't personally use `pushState` that much so having another set of eyes on it would be cool. I'm still planning on addressing this eventually though

**Comment by Fak3** [comment]
> Hey, thanks for bringing this to my attention. We used to trigger a page reload when navigating through history, but it looks like that got dropped in in v0.6. Anyway I think a more comprehensive solution is probably necessary now, I'll try to get something pushing in the next few days. In the meantime, you should be able to add the old v0.5 behavior back to your project with this event listener:
> 
> ```
> window.addEventListener('popstate', (e) => {
>   if (!e.state || !e.state.__ajax) return
> 
>   window.location.reload(true)
> })
> ```

Hmm, that conditional reload did not work for me, i had to reload it unconditionally:
```
window.addEventListener('popstate', (e) => {
  window.location.reload(true)
})
```

**Comment by imacrayon** [comment]
`x-target.push` functionality should be restored as of v0.10. I'm going to close this issue out but feel free to re-open it if you encounter any more problems with pushing history.
