### ISSUE TITLE
Console Error with Mock Server and Module CDN

### ISSUE THREAD

**Issue by 1sd15** [imacrayon/alpine-ajax#98]
Hey! First off I'd like to say that I love how the project has been presented and maintained. I hope to use it more soon!

I'm hitting a snag on my Codepen (https://codepen.io/1sd15/pen/zYgGYEZ) in which hitting the Mock Server gives me back `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString')` originating from the `statusKey` method. 

I believe that this could be due the Module CDN but it could also be a mistake I've overlooked. I'd love some assisstance if possible!

**Comment by imacrayon** [comment]
Hey! You'll get that error using an outdated version of the mock server. It looks like that Pen is including v0.9.1 of Alpine AJAX but only v0.2.0 for the server, as long as those version numbers match you should be good to go.

Thanks for bringing this to my attention though, the mock server could use some love, it's not the easiest thing to work with right now. I might try to get an update out this weekend.

Unfortunately, I'm not sure that the mock server code will play nice with ESM modules even after that version fix though. For the mock server to work routes need to be defined **before** the page's `DOMContentLoaded` event fires, and - if I remember correctly - I think module code runs after that event.

**Comment by 1sd15** [comment]
Hey @imacrayon thanks for getting back to me so fast! The updated version worked perfectly fine; seems that the routes in the module area worked okay? I should probably open a new thread but I can't get x-sync working on that Codepen; is there anything obvious that I'm doing wrong there 🤔

**Comment by imacrayon** [comment]
I think you just need to make sure that the `<div id="total">` returned in the server response also has an `x-sync` attribute.

**Comment by 1sd15** [comment]
Oh my gosh! That makes sense as it's like an outerHTML replace? That's all thank you for your help!
