### ISSUE TITLE
Question: how to achieve HTMX boost / Turbo Drive behaviour for page links?

### ISSUE THREAD

**Issue by bluz71** [imacrayon/alpine-ajax#99]
Hello,

Alpine AJAX is an interesting library which I only discovered today (my bad), especially since I have been a modest Alpine.JS for a while.

My question pertains to [HTMX Boost](https://htmx.org/attributes/hx-boost) and [Turbo Drive](https://turbo.hotwired.dev/handbook/drive#page-navigation-basics) behaviour. These technologies convert standard page to page links into AJAX requests that update the body whilst avoiding CSS / JS recomputes. These technologies avoid page flashes, lending a more SPA like feel which is very nice, even nicer when combined with View Transitions.

Alpine AJAX probably can achieve the same behaviour (including URL pushing), but since I am so new to this library, I am not sure how to do it. Ideally with a simple syntax?

Could an example be added? Maybe labelled _Page Navigation_?

Best regards.

**Comment by bluz71** [comment]
Hello Alpine AJAX,

After some research it appears Alpine AJAX deliberately does not provide a `hx-boost` like feature. This is noted by the library author on X with [this post](https://x.com/ima_crayon/status/1837181348588421570):

> One of the most common questions I get about Alpine AJAX is “why is there no `hx-boost`?”. It’s because you probably don’t need it! And if you’re not careful it can even make your apps worse. Navigation UX keeps getting better in browsers lately.

And [this one](https://x.com/ima_crayon/status/1821163907873919101) as well:

> There’s so many accessibility & state management foot guns in SPA navigation I’m not sure it’s the best approach. There’s cool alternative browser APIs like Speculative Loading & View Transitions  that are easier to implement without so many downsides.

So no HTMX Boost or Turbo Drive.

View Transitions recommended which Alpine AJAX already appears to provide.

I don't know much about Speculative Loading?

Is Link hover preloading possible in Alpine AJAX? Like the [HTMX Preload Extension](https://htmx.org/extensions/preload) or [Turbo Preload Links](https://turbo.hotwired.dev/handbook/drive#prefetching-links-on-hover).

I suspect the combination of Modern Browsers plus View Transistions plus Link Hover Preloading would be excellent.

Closing this, will open a new issue about Link Hover Preloading.

Cheers.

**Comment by bluz71** [comment]
Re-opening.

Question, how to enable View Transitions for page to page navigation in Alpine AJAX?

Seems like the current VT support is for merging on the current page as [documented here](https://alpine-ajax.js.org/reference/#view-transitions-and-animations):

> To enable View Transitions on an **element** use the x-merge.transition modifier. When enabled in a supported browser, you should see content automatically **animate as it is merged onto the page**.

Sorry for all the questions. I do think a page-to-page navigation solution would be of great benefit for this library. It may be the only thing missing that may force me to use HTMX instead.

Note, it may be totally legitimate to not care about that case.

My background is Rails with Turbolinks and Turbo Drive.

Since then I have become a fan of Alpine.js so Alpine AJAX is of interest, just page to page appears to be a blocker for me.

Will be interested to hear Alpine AJAX's thoughts on the matter.

Cheers.

**Comment by bluz71** [comment]
Maybe [swup.js](https://swup.js.org) is the recommended page to page solution?

**Comment by imacrayon** [comment]
[`@view-transition`](https://developer.mozilla.org/en-US/docs/Web/CSS/@view-transition) provides transitions across pages, unfortunately it's not available in Firefox yet, and it can't be polyfilled 👎 

So I'd say if page transitions are a "must-have" feature in your project, Swup might be the best way to go.

**Comment by bluz71** [comment]
Hello @imacrayon,

I feel this issue and #100 (preloading) are highly connected.

At the moment Alpine AJAX clearly is focussed on progressive enhancement for in-page/current-page partial/morphed modifications.

Alpine AJAX, for now, provides **no** progressive enhancement for Page-to-Page navigation .

In your posts on X you clearly believe `hx-boost` and `Turbo Drive` are not the correct solutions in 2024. My initial mindset for this issue dates back to a 2016 mentality when `Turbolinks` really did improve site ergonomics. After a bit of research, I tend to agree with your philosophy as posted on X (see quotes above). No `hx-boost` is correct for Alpine AJAX.

I have used View Transistions a little on a throw-away Astro project, and they were really nice for MPA (multi-page app). I want to use them for MPA projects when doing page to page navigation.

swup.js does now support native View Transistions, alongside a host of other capabilities.  However, it's unpacked size is `692kB` compared with Alpine.js at `543kB`. This does not thrill me.

View Transitions have been in Chrome (and Chrome derivative browsers) since 2023.
Safari support is coming very soon (commits have been done), I suspect late 2024 early 2025.
Firefox is supposedly starting work [in a couple of months](https://bugzilla.mozilla.org/show_bug.cgi?id=1909173).

What should Alpine AJAX offer? I say:

- Simple API for both Page to Page View Transistions & Link Preloading (#100)
- Or neither

As you note in #100 [Instant.page](https://instant.page) already exists for Link preloading.
[swup.js](https://swup.js.org) also exists for transitions, but seems quite bloated and I would be concerned about weird edge-cases with Alpine.js.

If there was a smaller View Transitions library, compatible with Alpine.js, that could be used that would be ideal.

Expanding Alpine AJAX brings it own risks, unnecessary risks if solutions exist.
 
Food for thought for you.

Think about it, then update this issue (and #100).

Best regards.

**Comment by bluz71** [comment]
@imacrayon,

I have gone down the View Transitions rabbit hole and have discovered Multi-Page View Transitions is a real thing. Absolutely mind blowing.

And page preloading can be done using Speculation Rules API, which Chrome already has.

[See this video](https://youtu.be/eY6C_-aDdTo?feature=shared) is a must watch.

Basically Alpine AJAX should not offer anything for page to page navigation, offload that to the Browser via Multi-Page View Transitions and Speculation Rules APIs.

**Comment by bluz71** [comment]
@imacrayon,

Ok, I tested Chrome/Brave browser Multi-Page View Transitions as discussed in the linked video above.

It works!!! And looks absolutely beautiful.

Just add this to the top level CSS file:

```css
  @view-transition {
    navigation: auto;
  }
```

Yes, that is all that is needed for modern Blink-engine browsers such as Chrome, Edge and Brave (since June 2024). An elegant fade happens between page changes, absolutely no flashes.

View Transitions currently exist in two forms, Same-Page transitions and Multi-Page transitions. This is my understanding of support:

- Modern Blink browsers (Chrome, Edge, Brave) support SP (2023 feature) and MP transitions (June 2024 feature)
- Safari will soon support SP transitions (commits already happened), MP transitions likely later on (I assume)
- Firefox, initial work started on SP transitions (will be the last to deliver this feature)
 
Browsers without MP View Transition support degrade gracefully to standard full page loads, which in modern browsers is not the issue that it used to be. View Transitions is progressive enhancement.

I am now fully convinced, [HTMX Boost](https://htmx.org/attributes/hx-boost) and [Turbo Drive](https://turbo.hotwired.dev/handbook/drive#page-navigation-basics) are solutions for yesterday's problem, and they come with a host of issues of their own (aka JS not reloading on page change).

MP transitions work really well with `speculationrules` page prerendering (aka, hover over a link for 200ms, page will download ready to immediately change), see [this comment](https://github.com/imacrayon/alpine-ajax/issues/100#issuecomment-2418531094).

Closing this issue, it is not needed with modern browsers.

**Comment by bluz71** [comment]
Hello @imacrayon,

Apple is, or has completed, work on Cross-Document View Transitions (aka Multi-Page View Transitions) in their repository.

Current release, version 18, does not support these transitions.

However, commits & fixes have occurred in Sept / Oct, see here:

- https://bugs.webkit.org/show_bug.cgi?id=278247
- https://bugs.webkit.org/show_bug.cgi?id=280703
- https://github.com/WebKit/WebKit/pull/35556

Safari support is coming which will be **HUGE** news  since all Browsers on iOS and iPadOS use the Safari / WebKit-rendering-engine.

I suspect the next Safari release will have MP VT.

I will keep an eye on this.
